exports.GATEWAY_URL = "https://route.lgthinq.com:46030/v1/service/application/gateway-uri";
exports.SVC_CODE = "SVC202";
exports.CLIENT_ID = "LGAO221A02";
exports.OAUTH_SECRET_KEY = "c053c2a6ddeb7ad97cb0eed0dcb31cf8";
exports.OAUTH_CLIENT_KEY = "LGAO722A02";
exports.API_KEY = "VGhpblEyLjAgU0VSVklDRQ==";
exports.API_CLIENT_ID = "0396d48364f9a25824a3121758b512686f0ead3a5a4349b5b76f0febcd1809ea";
exports.API1_CLIENT_ID = "00709966e14709a49926823120fe0807731383782187aa23b87fb70439fac1c8";

exports.APPLICATION_KEY = "6V1V8H2BN5P9ZQGOI5DAQ92YZBDO3EK9"; // for spx login

exports.PlatformType = {
    ThinQ1: "thinq1",
    ThinQ2: "thinq2",
};

exports.DeviceType = {
    REFRIGERATOR: 101,
    KIMCHI_REFRIGERATOR: 102,
    WATER_PURIFIER: 103,
    WASHER: 201,
    WASHER_2: 221,
    WASH_TOWER: 222,
    DRYER: 202,
    STYLER: 203,
    DISHWASHER: 204,
    OVEN: 301,
    MICROWAVE: 302,
    COOKTOP: 303,
    HOOD: 304,
    AC: 401, // Includes heat pumps, etc., possibly all HVAC devices.
    AIR_PURIFIER: 402,
    DEHUMIDIFIER: 403,
    ROBOT_KING: 501, // This is Robotic vacuum cleaner
    TV: 701,
    BOILER: 801,
    SPEAKER: 901,
    HOMEVU: 902,
    ARCH: 1001,
    MISSG: 3001,
    SENSOR: 3002,
    SOLAR_SENSOR: 3102,
    IOT_LIGHTING: 3003,
    IOT_MOTION_SENSOR: 3004,
    IOT_SMART_PLUG: 3005,
    IOT_DUST_SENSOR: 3006,
    EMS_AIR_STATION: 4001,
    AIR_SENSOR: 4003,
    PURICARE_AIR_DETECTOR: 4004,
    V2PHONE: 6001,
    HOMEROBOT: 9000,
};

exports.Translation = {
    BABYCARE: "Babybekleidung", 
    HYGIENE: "Hygiene", 
    SMALLLOAD: "Kleine Beladung", 
    LINGERIE: "Lingerie", 
    SKINCARE: "Hautpflege", 
    COLDWASH: "Kalt waschen", 
    RINSESPIN: "Spülen + Schleudern", 
    KIDSWEAR: "Kinderbekleidung", 
    SCHOOLUNIFORM: "Schuluniform", 
    SWIMMINGWEAR: "Badebekleidung", 
    RAINYSEASON: "Nasse Kleidung", 
    GYMCLOTHES: "Gymnastikbekleidung", 
    JEANS: "Jeans", 
    BLANKET: "Decke", 
    SWEATSTAIN: "Schweißflecken", 
    SINGLEGARMENT: "Einzelkleidungsstück", 
    COLORPROTECTION: "Farbschutz", 
    NOISEMINIMIZE: "Extra leise", 
    MINIMIZEWRINKLES: "Knitterschutz", 
    LIGHTLYSOILEDITEMS: "Leicht verschmutzte Wäsche", 
    MINIMIZEDETERGENT: "Waschmittelrückstände minimieren", 
    SLEEVEHEMSANDCOLLARS: "Hemden und Blusen", 
    JUICEANDFOODSTAINS: "Lebensmittel-Flecken", 
    QUICKTUBCLEAN: "Schnelle Tommelreinigung", 
    DRAIN: "Abpumpen", 
    SPIN: "Schleudern",
    COTTON: "Koch-/Buntwäsche", 
    EASYCARE: "Pflegeleicht", 
    COTTONPLUS: "ECO 40-60", 
    DUVET: "Bettdecken", 
    MIXEDFABRIC: "Mix", 
    SPORTSWEAR: "Sportbekleidung", 
    SILENTWASH: "Nachtprogramm", 
    SPEED14: "14 Minuten", 
    TUB_CLEAN: "Trommelreinigung", 
    WOOL: "Wolle", 
    DELICATE: "Feinwäsche", 
    ALLERGYSPASTEAM: "Allergy Care/Hygiene", 
    TURBO39: "39 Minuten",
    TURBO59: "59 Minuten",
    DRY: "Trocknen",
    DRY_COOLING: "Abkühlen",
    DRY_NORMAL: "Normales Trocknen",
    DRY_IRON: "Bügeln",
    DRY_ECO: "Öko-Trocknen",
    DRY_SPEED: "Schnell",
    DRY_LOW: "Niedrig",
    DRY_NORMAL_ECO: "Normaler Sparmodus",
    DRY_30: "Trockenzeit 30 Min.",
    DRY_60: "Trockenzeit 60 Min.",
    DRY_90: "Trockenzeit 90 Min.",
    DRY_120: "Trockenzeit 120 Min.",
    NO_SOILWASH: "Keine Verschmutzung",
    SOILWASH_TURBO_WASH: "Schwere Verschmutzung",
    SOILWASH_TIMESAVE: "Zeitsparen Verschmutzung",
    SOILWASH_NORMAL: "Normale Verschmutzung",
    SOILWASH_INTENSIVE: "Intensive Verschmutzung",
    NO_SPIN: "Schleudern aus",
    SPIN_400: "400 U/Min",
    SPIN_600: "600 U/Min",
    SPIN_700: "700 U/Min",
    SPIN_800: "800 U/Min",
    SPIN_900: "900 U/Min",
    SPIN_1000: "1000 U/Min",
    SPIN_1100: "1100 U/Min",
    SPIN_1200: "1200 U/Min",
    SPIN_1400: "1400 U/Min",
    SPIN_1600: "1600 U/Min",
    SPIN_Max: "Schleudern Max",
    NOT_SELECTED: "Keine Auswahl",
    TEMP_COLD: "Kalt",
    TEMP_20: "20°C",
    TEMP_30: "30°C",
    TEMP_40: "40°C",
    TEMP_50: "50°C",
    TEMP_60: "60°C",
    TEMP_95: "95°C",
    NO_TEMP: "Keine Auswahl",
    LOADITEM_OFF: "aus",
    LOADITEM_1: "Beladungsmenge 1",
    LOADITEM_2: "Beladungsmenge 2",
    LOADITEM_3: "Beladungsmenge 3",
    TURBOWASH_OFF: "Schnell waschen aus",
    TURBOWASH_ON: "Schnell waschen an",
    CREASECARE_OFF: "Knitterschutz aus",
    CREASECARE_ON: "Knitterschutz an",
    STEAMSOFTENER_OFF: "Dampf Weichspüler aus",
    STEAMSOFTENER_ON: "Dampf Weichspüler an",
    ECOHYBRID_OFF: "ECO aus",
    ECOHYBRID_ON: "ECO an",
    MEDICRINSE_OFF: "Medizinische Spülung aus",
    MEDICRINSE_ON: "Medizinische Spülung an",
    RINSE_SPIN_OFF: "Spülen und Schleudern aus",
    RINSE_SPIN_ON: "Spülen und Schleudern an",
    PREWASH_OFF: "Vorwäsche aus",
    PREWASH_ON: "Vorwäsche an",
    STEAM_OFF: "Dampf aus",
    STEAM_ON: "Dampf an",
    INITIAL_BIT_OFF: "Gewichtserkennung aus",
    INITIAL_BIT_ON: "Gewichtserkennung aus",
    REMOTE_START_OFF: "Fernzugriff aus",
    REMOTE_START_ON: "Fernzugriff aus",
    DOOR_LOCK_OFF: "Türverschluss aus",
    DOOR_LOCK_ON: "Türverschluss an",
    CHILDLOCK_OFF: "Kindersicherung aus",
    CHILDLOCK_ON: "Kindersicherung an",
    NO_RINSE: "Kein Spülen",
    RINSE_NORMAL: "Normal", 
    RINSE_PLUS: "Spülen+", 
    RINSE_PLUSPLUS: "Spülen++",
    RINSE_NORMAL_HOLD: "Normal Spülen",
    RINSE_PLUS_HOLD: "Normal Spülen+",
    courseFL24inchBaseTitan: "Programm", 
    smartCourseFL24inchBaseTitan: "Download Programm",
    proofing: "Imprägnieren",
    soilWash: "Verschmutzung",
    spin: "Schleudergang",
    temp: "Temperatur",
    rinse: "Spülen",
    reserveTimeHour: "Startzeit in Stunde(n)",
    reserveTimeMinute: "Startzeit in Minute(n)",
    loadItemWasher: "Beladungsmenge", 
    turboWash: "Kurz Waschen",
    creaseCare: "Knitterschutz",
    steamSoftener: "Dampf Weichspüler",
    ecoHybrid: "ECO Hybrid",
    medicRinse: "Medizinische Spülung",
    rinseSpin: "Spülen und Schleudern",
    preWash: "Vorwäsche",
    steam: "Dampf",
    initialBit: "Einschaltverzögerung",
    remoteStart: "Fernzugriff",
    doorLock: "Türverriegelung",
    childLock: "Kinderschutz"
};
