/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "test adapter settings": {
        en: "Adapter settings for Fritzbox DECT",
        de: "Adaptereinstellungen für Fritzbox DECT",
        ru: "Настройки адаптера для Fritzbox DECT",
        pt: "Configurações do adaptador para Fritzbox DECT",
        nl: "Adapterinstellingen voor Fritzbox DECT",
        fr: "Paramètres de l'adaptateur pour Fritzbox DECT",
        it: "Impostazioni dell'adattatore per Fritzbox DECT",
        es: "Ajustes del adaptador para Fritzbox DECT",
        pl: "Ustawienia adaptera dla Fritzbox DECT",
        "zh-cn": "Fritzbox DECT 的适配器设置",
    },
    "Server Username": {
        en: "Created username in the Fritzbox with Smarthome rights",
        de: "Erstellter Benutzername in der Fritzbox mit Smarthome Rechte",
        ru: "Создано имя пользователя в Fritzbox с правами Smarthome",
        pt: "Nome de usuário criado no Fritzbox com direitos Smarthome",
        nl: "Gebruikersnaam aangemaakt in de Fritzbox met Smarthome rechten",
        fr: "Nom d'utilisateur créé dans la Fritzbox avec les droits Smarthome",
        it: "Nome utente creato nel Fritzbox con diritti Smarthome",
        es: "Nombre de usuario creado en Fritzbox con derechos de SmarthomeP",
        pl: "Utworzono nazwę użytkownika w Fritzbox z uprawnieniami Smarthome",
        "zh-cn": "在具有 Smarthome 权限的 Fritzbox 中创建用户名",
    },
    "Server Password": {
        en: "Username password",
        de: "Passwort vom Benutzername",
        ru: "Имя пользователя Пароль",
        pt: "Usuário senha",
        nl: "Gebruikersnaam wachtwoord",
        fr: "Identifiant Mot de passe",
        it: "Nome utente password",
        es: "Usuario Contraseña",
        pl: "Nazwa uzytkownika Haslo",
        "zh-cn": "用户名密码",
    },
    "Server IP": {
        en: "IP of the Fritzbox",
        de: "IP der Fritzbox",
        ru: "IP-адрес Fritzbox",
        pt: "IP do Fritzbox",
        nl: "IP van de Fritzbox",
        fr: "IP de la Fritzbox",
        it: "IP del Fritzbox",
        es: "IP del Fritzbox",
        pl: "IP Fritzbox",
        "zh-cn": "Fritzbox 的 IP",
    },
    "Booster minutes": {
        en: "Booster time in minutes",
        de: "Booster Zeit in Minuten",
        ru: "Время бустера в минутах",
        pt: "Tempo de reforço em minutos",
        nl: "Boostertijd in minuten",
        fr: "Temps de rappel en minutes",
        it: "Tempo di richiamo in minuti",
        es: "Tiempo de refuerzo en minutos",
        pl: "Czas doladowania w minutach",
        "zh-cn": "以分钟为单位的助推器时间",
    },
    "Openr minutes": {
        en: "Window open time in minutes",
        de: "Fenster offen Zeit in Minuten",
        ru: "Время открытия окна в минутах",
        pt: "Tempo de abertura da janela em minutos",
        nl: "Raam open tijd in minuten",
        fr: "Temps d'ouverture de la fenêtre en minutes",
        it: "Tempo di apertura della finestra in minuti",
        es: "Tiempo de apertura de la ventana en minutos",
        pl: "Czas otwarcia okna w minutach",
        "zh-cn": "以分钟为单位的窗口打开时间",
    },
    "DECT Interval ALL": {
        en: "Interval for the complete update of the DECT devices in minutes",
        de: "Intervall für die komplette Aktualisierung der DECT Geräte in Minuten",
        ru: "Интервал для полного обновления устройств DECT в минутах",
        pt: "Intervalo para a atualização completa dos dispositivos DECT em minutos",
        nl: "Interval voor de volledige update van de DECT-apparaten in minuten",
        fr: "Intervalle pour la mise à jour complète des appareils DECT en quelques minutes",
        it: "Intervallo per l'aggiornamento completo dei dispositivi DECT in minuti",
        es: "Intervalo para la actualización completa de los dispositivos DECT en minutos",
        pl: "Odstep czasu na pelna aktualizacje urzadzen DECT w ciagu kilku minut",
        "zh-cn": "在几分钟内完成 DECT 设备更新的间隔",
    },
    "DECT Interval": {
        en: "Interval for changes to the DECT devices in seconds",
        de: "Intervall für Änderungen der DECT Geräte in Sekunden",
        ru: "Интервал изменения устройств DECT в секундах",
        pt: "Intervalo para mudanças nos dispositivos DECT em segundos",
        nl: "Interval voor wijzigingen aan de DECT-apparaten in seconden",
        fr: "Intervalle de modification des appareils DECT en quelques secondes",
        it: "Intervallo per le modifiche ai dispositivi DECT in secondi",
        es: "Intervalo para cambios en los dispositivos DECT en segundos",
        pl: "Interwal na zmiany w urzadzeniach DECT w sekundach",
        "zh-cn": "以秒为单位更改 DECT 设备的间隔",
    },
    "TEMP Interval": {
        en: "Interval for the update of the templates in hours",
        de: "Intervall für die Aktualisierung der Templates in Stunden",
        ru: "Интервал обновления шаблонов в часах",
        pt: "Intervalo para atualização dos templates em horas",
        nl: "Interval voor het bijwerken van de sjablonen in uren",
        fr: "Intervalle de mise à jour des modèles en heures",
        it: "Intervallo per l'aggiornamento dei modelli in ore",
        es: "Intervalo de actualización de las plantillas en horas",
        pl: "Interwał aktualizacji szablonów w godzinach",
        "zh-cn": "更新模板的时间间隔（以小时为单位）",
    },
    "HTTPS SSL": {
        en: "Enable HTTPS",
        de: "HTTPS aktiveren",
        ru: "Включить HTTPS",
        pt: "Habilitar HTTPS",
        nl: "HTTPS inschakelen",
        fr: "Activer HTTPS",
        it: "Abilita HTTPS",
        es: "Habilitar HTTPS",
        pl: "Wlacz HTTPS",
        "zh-cn": "启用 HTTPS",
    },
    "HTTPS cer": {
        en: "Fritzbox certificate",
        de: "Fritzbox Zertifikat",
        ru: "Сертификат Fritzbox",
        pt: "Certificado Fritzbox",
        nl: "Fritzbox-certificaat",
        fr: "Certificat Fritzbox",
        it: "Certificato Fritzbox",
        es: "Certificado Fritzbox",
        pl: "Certyfikat Fritzbox",
        "zh-cn": "Fritzbox 证书",
    },
    "Update Objects": {
    "en": "Update Fritzbox objects (once)",
    "de": "Fritzbox-Objekte aktualisieren (einmal)",
    "ru": "Обновить объекты Fritzbox (один раз)",
    "pt": "Atualizar objetos Fritzbox (uma vez)",
    "nl": "Fritzbox-objecten bijwerken (eenmalig)",
    "fr": "Mettre à jour les objets Fritzbox (une fois)",
    "it": "Aggiorna oggetti Fritzbox (una volta)",
    "es": "Actualizar objetos Fritzbox (una vez)",
    "pl": "Aktualizuj obiekty Fritzbox (jednorazowo)",
    "zh-cn": "更新 Fritzbox 对象（一次）"
    },
};
